### PR TITLE
Add `Comment` field to donors

### PR DESCRIPTION
**Pull request by morenoh149**
* add comment string to Donor model
* add comment textarea element to charge form
* change leaderboard from ordered list to table. Gives us
equidistant spacing for free.

closes https://github.com/patrickod/noisebridge-donate/issues/4

### CODE REVIEW

**Comment by morenoh149** [comment]
Wasn't able to test it properly but I think it's right. Should make a `db/seeds.rb` file.

**Comment by morenoh149** [comment]
force pushed an amend. That's why the diff looks funky.

**Comment by patrickod** [comment]
This also needs a migration for the comment column on donor?

**Comment by morenoh149** [comment]
added the migration file @patrickod

**Comment by patrickod** [comment]
Going to leave this out for the moment.

**Pull request closed without merging**
