### PR TITLE
Make it responsive

### PR DESCRIPTION
**Pull request by morenoh149**
* addresses https://github.com/patrickod/noisebridge-donate/issues/26
* added https://github.com/ai/autoprefixer-rails for vendor prefixes
(needed for flexbox on safari)
* made layout responsive
* fixed form inputs on safari

### CODE REVIEW

**Comment by morenoh149** [comment]
@patrickod didn't test it on pages other than the landing page. Don't know how to load those pages locally.

**Comment by patrickod** [comment]
neat, will check this out later tonight

**Comment by patrickod** [comment]
any idea what the merge conflict is? maybe rebasing on master?

**Comment by morenoh149** [comment]
Yeah I was developing on an old version of the project. Have you shared a gpg somewhere? Can't run the server without it. Unless I'm mistaken https://github.com/AGWA/git-crypt#using-git-crypt

**Pull request closed without merging**
